# Generated by Django 5.0.7 on 2024-08-17 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_language_alter_field_name_post_language'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='tag',
            field=models.ManyToManyField(blank=True, null=True, to='posts.tag'),
        ),
    ]
